name: linter

on: push

jobs:
  lint:
    name: linter
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2  

    - name: run lint
      uses: super-linter/super-linter@v7.1.0
      env:
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
